### ISSUE TITLE
Interpreter's private functions

### ISSUE THREAD

**Issue by m3m0ry** [dlang-community/drepl#87]
Is there any reason to have the functionality of [interpreter](https://github.com/dlang-community/drepl/blob/master/src/drepl/interpreter.d#L77) `classify` and `parse` behind `private`?

I am trying to use `drepl` for my [project](https://github.com/m3m0ry/dlang-jupyter) and I would love to have this functionality.

**Comment by PetarKirov** [comment]
Fixed by #88.
